# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Auroraboreas < Formula
  desc "Aurora Boreas - Poesia e visualização de céu estrelado"
  homepage "https://github.com/nataliagranato/auroraboreas"
  version "1.0.2"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/nataliagranato/auroraboreas/releases/download/v1.0.2/auroraboreas-1.0.2-darwin-amd64.tar.gz"
      sha256 "299d38481056ec35267b01d63c8df97c84ae3e840ed314d7ad78678887b88d10"

      def install
        bin.install "aurora"
      end
    end
    on_arm do
      url "https://github.com/nataliagranato/auroraboreas/releases/download/v1.0.2/auroraboreas-1.0.2-darwin-arm64.tar.gz"
      sha256 "240a25362d8ac8c6948b63313217f877c43f4b3bbe1085a73a29ccc09acdd8b7"

      def install
        bin.install "aurora"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nataliagranato/auroraboreas/releases/download/v1.0.2/auroraboreas-1.0.2-linux-amd64.tar.gz"
        sha256 "ba8d826a74bb1026ec6667781c3fc69dad9563946984ce02a3f29681faab8937"

        def install
          bin.install "aurora"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/nataliagranato/auroraboreas/releases/download/v1.0.2/auroraboreas-1.0.2-linux-armv6.tar.gz"
        sha256 "db70f4115515e50e32101cfb7a4ca11b8700e5dee04fd7ab9e832508eb79257e"

        def install
          bin.install "aurora"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nataliagranato/auroraboreas/releases/download/v1.0.2/auroraboreas-1.0.2-linux-arm64.tar.gz"
        sha256 "70a99ead5a10a96a44e5c5a628011fa10f8ac7d5205600e39d59fa9df0124df8"

        def install
          bin.install "aurora"
        end
      end
    end
  end

  test do
    system "#{bin}/aurora", "--version"
  end
end
