# This file is auto-generated by GoReleaser
# Do not edit manually
class Auroraboreas < Formula
  desc "Aurora Boreas - Poesia e visualização de céu estrelado"
  homepage "https://github.com/nataliagranato/auroraboreas"
  version "0.1.0"
  
  # This will be updated by GoReleaser
  url "https://github.com/nataliagranato/auroraboreas/releases/download/v0.1.0/auroraboreas-v0.1.0-darwin-amd64.tar.gz"
  sha256 "placeholder"
  
  def install
    bin.install "aurora"
  end

  test do
    system "#{bin}/aurora", "--version"
  end
end
